name: goatrik_hub
description: A feature-rich Flutter application by GoatrikWorks
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & DI
  provider: ^6.0.5
  get_it: ^8.0.1

  # Design & UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^3.1.3
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^0.69.0

  # Navigation
  go_router: ^14.3.0

  # Storage & Data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.2

  # Networking
  dio: ^5.3.2
  connectivity_plus: ^6.1.0

  # Utils
  logger: ^2.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  timeago: ^3.2.2
  flutter_dotenv: ^5.0.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/